name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行一次同步
  workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master  # 修改为你的实际主分支名（master）
          fetch-depth: 0

      - name: Set up Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/fesiong/anqicms.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master  # 修改为你的实际主分支名（master）
          git merge upstream/master --no-edit  # 修改为上游仓库的实际主分支名

      - name: Push changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master  # 修改为你的实际主分支名（master）
